{"uuid": "96d0ddac-c1ae-4d3f-a477-3837862642fa", "children": ["16818f8a-73f1-4ead-a7f5-f8acf2f56e32"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Invalid Host header localhost:36097\n\n", "trace": "  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/_pytest/fixtures.py\", line 910, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/nsl42/Desktop/Automation/PhpTravels/tests/conftest.py\", line 18, in browser\n    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install())) # chrome_options=options)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py\", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/nsl42/anaconda3/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1729068565362, "stop": 1729068571604}], "start": 1729068565362, "stop": 1729068571637}